LEXICON_RU: dict[str, str] = {
    '/start': '',
    '/help': '',
    'registration_start': 'Для начала работы с ботом нужно зарегистрироваться. Это нужно для персонализации результатов. '
                    '\nДля старта регистрации вызовите команду /registrate',
    'registration_error': 'Вы не зарегистрированы. \nДля старта регистрации вызовите команду /registrate',
    'registration_command': 'Приветствую в системе регистрации. Ответьте на несколько простых вопросов',
    'registration_card': 'У вас есть Ozon карта?',
    'registration_card_error': 'Ошибка. Ответьте на вопрос "да" или "нет"',
    'registration_variation': 'Показывать ли вариации товара на его страничке?',
    'registration_variation_only_cheap': 'Только более дешёвые',
    'registration_variation_error': 'Ошибка. Ответьте на вопрос "да", "нет" или "только более дешёвые"',
    'registration_image': 'Показывать ли изображение товара на его страничке?',
    'registration_image_error': 'Ошибка. Ответьте на вопрос "да" или "нет"',
    'registration_notifications': 'Присылать ли вам уведомлении при изменении цены на товар из избранного?',
    'registration_notifications_only_lowering': 'Только при понижении цены',
    'registration_notifications_error': 'Ошибка. Ответьте на вопрос "да", "нет" или "только про понижения цены"',
    'registration_finish': 'Регистрация успешно завершена!',
    'main_menu': 'Главное меню',
    'main_menu_products': 'Посмотреть цену на продукт',
    'main_menu_settings': 'Настройки',
    'main_menu_favorites': 'Избранное',
    'main_menu_admin_users': 'Статистика пользователей',
    'main_menu_admin_products': 'Статистика товаров',
    'yes': 'Да',
    'no': 'Нет',
}
