LEXICON_EN: dict[str, str] = {
    'help_command': 'This is a bot for tracking product prices on Ozon. To start it, type /start',
    'random_message': 'That`s not exactly how it works... To interact with the bot, type /start',
    'registration_start': 'To start using the bot, you need to register. This is necessary for personalizing the results. '
                    '\nTo start the registration process, use the command /registrate',
    'registration_error': 'You are not registered. \nTo start registration, use the command /registrate',
    'registration_command': 'Welcome to the registration system. Please answer a few simple questions',
    'registration_card': 'Do you have an Ozon card?',
    'registration_card_error': 'Error. Please answer the question with "yes" or "no"',
    'registration_variation': 'What variations of the product should be displayed?',
    'registration_variation_error': 'Error. Please answer with "all" or "only cheaper ones"',
    'registration_notifications': 'Would you like to receive notifications when the price of a product in your favorites changes?',
    'registration_notifications_error': 'Error. Please answer with "yes," "no," or "only about price decreases"',
    'registration_finish': 'Registration successfully completed!',
    'registration_already_completed': 'You are already registered',
    'main_menu_hello': 'Hello, {event.from_user.username}!',
    'main_menu_hello_2': 'Choose an action',
    'main_menu_products': '👁️ View product price',
    'main_menu_settings': '⚙️ Settings',
    'main_menu_favorites': '⭐ Favorites',
    'main_menu_statistics': '📊 Statistics',
    'main_menu_add_admin': '➕ Add admin',
    'main_menu_about': 'ℹ️ About the app',
    'about': 'This bot allows you to track prices of products on Ozon. \nIt is written in aiogram as a coursework project \n\nAuthor: @csharpguy',
    'statistics_users': 'Number of users: {users_count}',
    'statistics_products': 'Number of products: {products_count}',
    'statistics_brands': 'Number of sellers: {sellers_count}',
    'add_admin': 'Please send the account name of the new admin',
    'admin_added': 'The admin has been successfully added!',
    'admin_add_error': 'A user with that name does not exist. Please try again',
    'settings_all': 'User settings {event.from_user.username}',
    'settings_have_card': 'Ozon card availability',
    'have_card_description': 'Depending on whether you have an Ozon card or not, you will see the corresponding prices for the products',
    'have_card_checkbox': 'Ozon card',
    'settings_show_variations': 'Product options display',
    'show_variations_description': 'Along with detailed product information, a list of product options will also be displayed',
    'settings_show_image': 'Show product image',
    'show_image_description': 'When the setting is enabled, the product image will be displayed along with the price change chart',
    'show_image_checkbox': 'Show product image',
    'settings_send_notifications': 'Notifications',
    'send_notifications_description': 'You will receive a notification when the price of a product changes',
    'product_get_id': 'Send me the link to the product or its article number. \nAlternatively, just write the product name, and I will try to find possible options for you',
    'favorites_show': 'List of your favorite products. Click on a product for more details',
    'favorites_edit': 'Click on the product to remove it from favorites',
    'UserShowVariations.all': 'All',
    'UserShowVariations.only_cheaper': 'Only cheaper ones',
    'UserSendNotifications.yes': 'Send',
    'UserSendNotifications.no': 'Do not send',
    'UserSendNotifications.only_lowering': 'Send only when the price decreases',
    'product_search': 'The following results were found for the query "{dialog_data[search_query]}"',
    'product_search_error': 'No results were found for the query "{dialog_data[search_query]}"',
    'product_id_error': 'There is no product with such an article number',
    'product_price_have_card': 'The current price is: {dialog_data[product][card_price]} rubles',
    'product_price_no_card': 'The current price is: {dialog_data[product][regular_price]} rubles',
    'product_variant_have_card': '{item[card_price]} rub. — {item[title]}',
    'product_variant_no_card': '{item[regular_price]} rub. — {item[title]}',
    'product_rating_count': '★ {dialog_data[product][rating]} • {dialog_data[product][rating_count]} reviews',
    'product_no_variations': 'There are no options',
    'product_show_variations': '🔢 Show options',
    'product_hide_variations': '↪️ Hide options',
    'product_to_favorites': '⭐ Add to favorites',
    'product_from_favorites': '⭐ Remove from favorites',
    'product_show_image': '📷 Show product photo',
    'product_show_graph': '📈 Show price chart.',
    'favorites_edit_button': '✏️ Edit',
    'favorites_empty': 'You have no products in favorites.',
    'notification': '🔔 Price on product {product} changed from {old_price} to {new_price}!',
    'notification_button': 'Open product page',
    'graph_green': 'In stock',
    'graph_gray': 'Out of stock',
    'cancel': '❌ Cancel',
    'close': '❌ Close',
    'back': '⬅️ Back',
    'yes': 'Yes',
    'no': 'No',
    'rub': 'rub.',
}
